version: "3.8"

services:
  db:
    image: postgres:15
    container_name: aipersona_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aipersona_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - aipersona_net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aipersona_backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - aipersona_net
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  db_data:

networks:
  aipersona_net:
    driver: bridge
